version: "3"

services:
  fluentd:
    build:
      context: .
      dockerfile: DockerFile.fluentd

    volumes:
      # 호스트 시스템의 './fluentd/conf' 디렉토리를
      # 컨테이너의 '/fluentd/etc/fluentd' 디렉토리에 마운트합니다.
      # 이를 통해 Fluentd 설정 파일을 컨테이너에 제공할 수 있습니다.
      - ./fluentd/conf:/fluentd/etc/fluentd
      # 호스트 시스템의 './fluentd/log' 디렉토리를
      # 컨테이너의 '/fluentd/log' 디렉토리에 마운트합니다.
      # 이를 통해 로그 파일을 컨테이너 밖으로 보낼 수 있습니다.
      - ./fluentd/log:/fluentd/log

    # 컨테이너가 사용할 포트를 정의합니다.
    ports:
      # 호스트의 24224 포트를 컨테이너의 24224 포트에 연결합니다 (TCP).
      - "24224:24224"
      # 호스트의 24224 포트를 컨테이너의 24224 포트에 연결합니다 (UDP).
      - "24224:24224/udp"

    # 컨테이너가 실패할 경우 자동으로 재시작하도록 설정합니다.
    restart: always
